const ADMIN_UID = "3jC9pWkF5ZeHIDtd1LrPR1Ptvbz1";
const FIREBASE_PROJECT_ID = "reps-central";
const FIREBASE_ISSUER = `https://securetoken.google.com/${FIREBASE_PROJECT_ID}`;
const FIREBASE_JWKS_URL = "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com";
const INDEX_KEY = "catalog/index.json";
function json(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json; charset=utf-8",...headers}})}
function decodeBase64Url(value){const normalized=value.replace(/-/g,"+").replace(/_/g,"/");const padded=normalized+"=".repeat((4-(normalized.length%4))%4);const binary=atob(padded);return new Uint8Array([...binary].map(char=>char.charCodeAt(0)))}
function decodeJsonPart(value){return JSON.parse(new TextDecoder().decode(decodeBase64Url(value)))}
async function verifyFirebaseIdToken(idToken){const parts=idToken.split(".");if(parts.length!==3)return null;let header,payload;try{header=decodeJsonPart(parts[0]);payload=decodeJsonPart(parts[1])}catch{return null}if(header.alg!=="RS256"||!header.kid)return null;const now=Math.floor(Date.now()/1000);if(payload.aud!==FIREBASE_PROJECT_ID||payload.iss!==FIREBASE_ISSUER)return null;if(typeof payload.sub!=="string"||!payload.sub)return null;if(typeof payload.exp!=="number"||payload.exp<=now)return null;if(typeof payload.iat!=="number"||payload.iat>now+300)return null;let jwks;try{const response=await fetch(FIREBASE_JWKS_URL,{cf:{cacheTtl:3600,cacheEverything:true}});if(!response.ok)return null;jwks=await response.json()}catch{return null}const jwk=jwks.keys?.find(key=>key.kid===header.kid);if(!jwk)return null;try{const publicKey=await crypto.subtle.importKey("jwk",jwk,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);const signedData=new TextEncoder().encode(`${parts[0]}.${parts[1]}`);const signature=decodeBase64Url(parts[2]);const valid=await crypto.subtle.verify("RSASSA-PKCS1-v1_5",publicKey,signature,signedData);return valid?payload:null}catch{return null}}
async function isAdmin(request){const header=request.headers.get("Authorization")||"";const token=header.startsWith("Bearer ")?header.slice(7).trim():"";if(!token)return false;const payload=await verifyFirebaseIdToken(token);return payload?.sub===ADMIN_UID||payload?.user_id===ADMIN_UID}
function normalizeIndexItem(item){const id=String(item?.id||"").trim();if(!id)return null;return{id,name:String(item?.name||""),category:String(item?.category||""),brand:String(item?.brand||""),sortOrder:Number(item?.sortOrder||0),isActive:item?.isActive!==false}}
async function readIndex(bucket){const object=await bucket.get(INDEX_KEY);if(!object)return{version:0,updatedAt:null,items:[]};try{const parsed=JSON.parse(await object.text());return{version:Number(parsed?.version||0),updatedAt:parsed?.updatedAt||null,items:Array.isArray(parsed?.items)?parsed.items.map(normalizeIndexItem).filter(Boolean):[]}}catch{return{version:0,updatedAt:null,items:[]}}}
async function writeIndex(bucket,index){const payload={version:Date.now(),updatedAt:new Date().toISOString(),items:index.items};await bucket.put(INDEX_KEY,JSON.stringify(payload),{httpMetadata:{contentType:"application/json; charset=utf-8",cacheControl:"no-cache"}});return payload}
export async function onRequestGet({env}){if(!env.CATALOG_INDEX_BUCKET)return json({error:"CATALOG_INDEX_BUCKET R2 binding is not configured."},503,{"Cache-Control":"no-store"});const object=await env.CATALOG_INDEX_BUCKET.get(INDEX_KEY);if(!object)return json({error:"Catalog index has not been generated yet.",items:[]},404,{"Cache-Control":"no-store"});const headers=new Headers();object.writeHttpMetadata(headers);headers.set("Content-Type","application/json; charset=utf-8");headers.set("Cache-Control","no-cache");if(object.httpEtag)headers.set("ETag",object.httpEtag);return new Response(object.body,{headers})}
export async function onRequestPost({request,env}){if(!(await isAdmin(request)))return json({error:"Unauthorized"},401,{"Cache-Control":"no-store"});if(!env.CATALOG_INDEX_BUCKET)return json({error:"CATALOG_INDEX_BUCKET R2 binding is not configured."},503,{"Cache-Control":"no-store"});let body;try{body=await request.json()}catch{return json({error:"Invalid JSON body."},400,{"Cache-Control":"no-store"})}const action=String(body?.action||"").toLowerCase();const current=await readIndex(env.CATALOG_INDEX_BUCKET);const map=new Map(current.items.map(item=>[item.id,item]));if(action==="replace"){if(!Array.isArray(body.items))return json({error:"items must be an array."},400,{"Cache-Control":"no-store"});map.clear();for(const raw of body.items){const item=normalizeIndexItem(raw);if(item)map.set(item.id,item)}}else if(action==="upsert"){const raw=body?.item||{};const id=String(raw.id||"").trim();if(!id)return json({error:"A valid item is required."},400,{"Cache-Control":"no-store"});const existing=map.get(id)||{id,name:"",category:"",brand:"",sortOrder:0,isActive:true};const merged=normalizeIndexItem({...existing,...raw,id});map.set(id,merged)}else if(action==="remove"){const id=String(body?.id||"").trim();if(!id)return json({error:"id is required."},400,{"Cache-Control":"no-store"});map.delete(id)}else{return json({error:"action must be replace, upsert or remove."},400,{"Cache-Control":"no-store"})}const items=[...map.values()].sort((a,b)=>Number(a.sortOrder||0)-Number(b.sortOrder||0));const saved=await writeIndex(env.CATALOG_INDEX_BUCKET,{items});return json({ok:true,version:saved.version,count:saved.items.length},200,{"Cache-Control":"no-store"})}
